### ISSUE TITLE
Send messages to IoT Hub instead of sockets

### ISSUE THREAD

**Issue by codefoster** [regatta-app/device#5]
in index.ts where we're currently calling socket.send
use AMQP
See https://github.com/codefoster/simple-iot-hub/blob/master/simdevice/index.js

**Comment by DanielEgan** [comment]
I have two issues... 

1. The free IoT hub tier only allows 8000 requests a day.  I almost used all that with one device while barely running.  We need to upgrade to S1 at least.
2.Trying to figure out an elegant way to pass in deviceID and Key which are needed for each device for the connection to IoThub.   For each rower, these need to be passed in via environment variables or another method.  

Let me know what you think.

**Comment by DanielEgan** [comment]
Upgraded IoT hub to next level  and used a local config file for the connection strings needed for the devices (not checked into source)

**Comment by codefoster** [comment]
Create a pull request

**Comment by codefoster** [comment]
It doesn't all have to be working for you to create a pull request. It just makes it easy for us to see and discuss the changes.

**Comment by codefoster** [comment]
Closing this. So far it sends _both_ the IoT Hub message and the socket message.
